<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BRAGIN2" name="com.example.tests.GroupEditTests" tests="7" failures="0" timestamp="15 Jul 2015 11:56:00 GMT" time="6.243" errors="2">
  <testcase name="testFullGroupEdit" time="1.253" classname="com.example.tests.GroupEditTests"/>
  <testcase name="testFullGroupEdit" time="0.769" classname="com.example.tests.GroupEditTests">
    <error type="java.lang.AssertionError" message="
Expected: &lt;[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name527195193], ObjGroup [name=TestGroup1]]&gt;
     but: was &lt;[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name-207235156], ObjGroup [name=test_group_name527195193]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name527195193], ObjGroup [name=TestGroup1]]]]><![CDATA[>
     but: was <[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name-207235156], ObjGroup [name=test_group_name527195193]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.example.tests.GroupEditTests.testFullGroupEdit(GroupEditTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testFullGroupEdit -->
  <testcase name="testFullGroupEdit" time="0.765" classname="com.example.tests.GroupEditTests"/>
  <testcase name="testNotValidGroupEdit" time="0.834" classname="com.example.tests.GroupEditTests"/>
  <testcase name="testFullGroupEdit" time="0.837" classname="com.example.tests.GroupEditTests">
    <error type="java.lang.AssertionError" message="
Expected: &lt;[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name-207235156], ObjGroup [name=test_group_name527195193], ObjGroup [name=TestGroup2]]&gt;
     but: was &lt;[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name-207235156], ObjGroup [name=test_group_name527195193], ObjGroup [name=TestGroup1]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name-207235156], ObjGroup [name=test_group_name527195193], ObjGroup [name=TestGroup2]]]]><![CDATA[>
     but: was <[ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=], ObjGroup [name=Group1ToDelede2], ObjGroup [name=Group1ToDelede3], ObjGroup [name=test_group_name-207235156], ObjGroup [name=test_group_name527195193], ObjGroup [name=TestGroup1]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.example.tests.GroupEditTests.testFullGroupEdit(GroupEditTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testFullGroupEdit -->
  <testcase name="testFullGroupEdit" time="0.772" classname="com.example.tests.GroupEditTests"/>
  <testcase name="testPartGroupEdit" time="1.013" classname="com.example.tests.GroupEditTests"/>
</testsuite> <!-- com.example.tests.GroupEditTests -->
